version: '3'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
  comments:
    build: ./comments
    ports:
      - "5001:5001"
    volumes:
      - ./comments:/app
  posts:
    build: ./posts
    ports:
      - "5002:5002"
    volumes:
      - ./posts:/app
  auth:
    build: ./auth
    ports:
      - "5003:5003"
    volumes:
      - ./auth:/app
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - comments
      - posts
      - auth
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml