version: '3'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
  comments:
    build: ./comments
    ports:
      - "5001:5001"
    volumes:
      - ./comments:/app
  posts:
    build: ./posts
    ports:
      - "5002:5002"
    volumes:
      - ./posts:/app
  auth:
    build: ./auth
    ports:
      - "5003:5003"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - comments
      - posts
      - auth
  syslog-ng:
    image: lscr.io/linuxserver/syslog-ng:latest
    container_name: syslog-ng
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /path/to/config:/config
      - /path/to/log:/var/log #optional
    ports:
      - 514:5514/udp
      - 601:6601/tcp
      - 6514:6514/tcp
    restart: unless-stopped